### ISSUE TITLE
Doug Self Preamp

### ISSUE THREAD

**Issue by MarcoRavich** [gkeeth/preamp-2019#1]
Hi there, sorry for the "issue" bu I don't know how to keep in touch with you.

This project is really interesting, even if - to me - would be great to have a tube-enabled preamp (such as [Freya by Sciit](https://www.schiit.com/products/freya))...

I do also suggest you to keep an eye on [Doug Self Preamp from Linear Audio #5](https://www.diyaudio.com/forums/analog-line-level/280458-doug-self-preamp-linear-audio-5-a.html) 3AD @ diyAudio to obtain more hints on build.

Last but not least, consider an adequate open license for your work.

Marco

**Comment by gkeeth** [comment]
Hi Marco,

Thanks for reaching out! I'm really sorry it took me so long to get back to you.

Thanks for the link. I'm reading through the thread and will keep an eye out for construction ideas.

Thanks for the prodding on licensing! I planned to release it with an open source license but hadn't decided on which license to use, until you brought it up. I just decided on a CC-BY-SA license and will update the project accordingly.
